# Generated by Django 4.1.1 on 2023-03-05 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='basicexportconfig',
            name='ccn_inssjp',
            field=models.CharField(max_length=20, verbose_name='Código de Concepto INSSJP'),
        ),
        migrations.AlterField(
            model_name='basicexportconfig',
            name='ccn_no_osysind',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de Concepto NR OS y Sind'),
        ),
        migrations.AlterField(
            model_name='basicexportconfig',
            name='ccn_no_rem',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de Concepto NR'),
        ),
        migrations.AlterField(
            model_name='basicexportconfig',
            name='ccn_no_sind',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de Concepto NR Sind.'),
        ),
        migrations.AlterField(
            model_name='basicexportconfig',
            name='ccn_os',
            field=models.CharField(max_length=20, verbose_name='Código de Concepto OS'),
        ),
        migrations.AlterField(
            model_name='basicexportconfig',
            name='ccn_sijp',
            field=models.CharField(max_length=20, verbose_name='Código de Concepto SIJP'),
        ),
        migrations.AlterField(
            model_name='basicexportconfig',
            name='ccn_sindicato',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de Concepto Sindicato'),
        ),
        migrations.AlterField(
            model_name='basicexportconfig',
            name='ccn_sueldo',
            field=models.CharField(max_length=20, verbose_name='Código de Concepto Sueldo'),
        ),
    ]
