# Generated by Django 4.1.7 on 2023-03-08 07:04

from django.db import migrations, models
import export_lsd.validators


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0004_alter_empleado_cuil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='name',
            field=models.CharField(default='Empleado', max_length=120,
                                   validators=[export_lsd.validators.validate_name], verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
