# Generated by Django 4.1.7 on 2023-03-08 07:05

from django.db import migrations, models
import export_lsd.validators


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0005_alter_empleado_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cuil',
            field=models.CharField(max_length=11, validators=[export_lsd.validators.validate_cuil]),
        ),
    ]
