# Generated by Django 4.1.7 on 2023-03-18 17:17

from django.db import migrations, models
import export_lsd.validators


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0006_alter_empleado_cuil'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cbu',
            field=models.CharField(blank=True, max_length=22, null=True,
                                   validators=[export_lsd.validators.validate_cbu], verbose_name='CBU'),
        ),
    ]
