# Generated by Django 4.1.7 on 2023-03-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0007_empleado_cbu'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='forma_pago',
            field=models.CharField(choices=[('1', 'Efectivo'), ('2', 'Cheque'),
                                            ('3', 'Acreditación')], default='1', max_length=1, verbose_name='Forma de Pago'),
        ),
    ]
