# Generated by Django 4.1.7 on 2023-04-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0008_liquidacion_forma_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='leg',
            field=models.IntegerField(),
        ),
    ]
