# Generated by Django 4.1.13 on 2023-11-05 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("export_lsd", "0010_empleado_created_empleado_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conceptoliquidacion",
            name="empleado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conceptos",
                to="export_lsd.empleado",
            ),
        ),
    ]
