# Generated by Django 5.2.13 on 2026-04-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='dato2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
