# Generated by Django 4.1.13 on 2024-05-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='mes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='nro_doc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='presentacion_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
