# Generated by Django 4.1.13 on 2024-05-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_remove_registro_presentacion_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regacceso',
            name='presentacion_version',
        ),
        migrations.AddField(
            model_name='registro',
            name='presentacion_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
