TABLA_TIPOREGISTRO = [
    {'id': 1, 'name': 'Datos referenciales del envío (Liquidación de SyJ y datos para DJ F931)', 'order': 1},
    {'id': 2, 'name': 'Datos referenciales de la Liquidación de SyJ del trabajador', 'order': 2},
    {'id': 3, 'name': 'Detalle de los conceptos de sueldo liquidados al trabajador', 'order': 3},
    {'id': 4, 'name': 'Datos del trabajador para el calculo de la DJ F931', 'order': 4},
    {'id': 5, 'name': 'Datos del trabajador de la empresa de servicios eventuales - Dec 342/1992', 'order': 5},
]

TABLA_FORMATO931 = [
    {'id': 425, 'name': 'CUIL', 'fromm': 1, 'long': 11},
    {'id': 426, 'name': 'Apellido y Nombre', 'fromm': 12, 'long': 30},
    {'id': 427, 'name': 'Cónyuge', 'fromm': 42, 'long': 1},
    {'id': 428, 'name': 'Cantidad de Hijos', 'fromm': 43, 'long': 2},
    {'id': 429, 'name': 'Codigo de Situación', 'fromm': 45, 'long': 2},
    {'id': 430, 'name': 'Codigo de Condición', 'fromm': 47, 'long': 2},
    {'id': 431, 'name': 'Código de Actividad', 'fromm': 49, 'long': 3},
    {'id': 432, 'name': 'Código de Zona', 'fromm': 52, 'long': 2},
    {'id': 433, 'name': 'Porcentaje de Aporte Adicional SS', 'fromm': 54, 'long': 5},
    {'id': 434, 'name': 'Código de Modalidad de Contratación', 'fromm': 59, 'long': 3},
    {'id': 435, 'name': 'Código de Obra Social', 'fromm': 62, 'long': 6},
    {'id': 436, 'name': 'Cantidad de Adherentes', 'fromm': 68, 'long': 2},
    {'id': 437, 'name': 'Remuneración Total', 'fromm': 70, 'long': 12},
    {'id': 438, 'name': 'Remuneración Imponible 1', 'fromm': 82, 'long': 12},
    {'id': 439, 'name': 'Asignaciones Familiares Pagadas', 'fromm': 94, 'long': 9},
    {'id': 440, 'name': 'Importe Aporte Voluntario', 'fromm': 103, 'long': 9},
    {'id': 441, 'name': 'Importe Adicional OS', 'fromm': 112, 'long': 9},
    {'id': 442, 'name': 'Importe Excedentes Aportes SS', 'fromm': 121, 'long': 9},
    {'id': 443, 'name': 'Importe Excedentes Aportes OS', 'fromm': 130, 'long': 9},
    {'id': 444, 'name': 'Provincia Localidad', 'fromm': 139, 'long': 50},
    {'id': 445, 'name': 'Remuneración Imponible 2', 'fromm': 189, 'long': 12},
    {'id': 446, 'name': 'Remuneración Imponible 3', 'fromm': 201, 'long': 12},
    {'id': 447, 'name': 'Remuneración Imponible 4', 'fromm': 213, 'long': 12},
    {'id': 448, 'name': 'Código de Siniestrado', 'fromm': 225, 'long': 2},
    {'id': 449, 'name': 'Marca de Corresponde Reducción', 'fromm': 227, 'long': 1},
    {'id': 450, 'name': 'Capital de Recomposición de LRT', 'fromm': 228, 'long': 9},
    {'id': 451, 'name': 'Tipo de empresa', 'fromm': 237, 'long': 1},
    {'id': 452, 'name': 'Aporte Adicional de Obra Social', 'fromm': 238, 'long': 9},
    {'id': 453, 'name': 'Regimen', 'fromm': 247, 'long': 1},
    {'id': 454, 'name': 'Situación de Revista 1', 'fromm': 248, 'long': 2},
    {'id': 455, 'name': 'Dia inicio Situación de Revista 1', 'fromm': 250, 'long': 2},
    {'id': 456, 'name': 'Situación de Revista 2', 'fromm': 252, 'long': 2},
    {'id': 457, 'name': 'Dia inicio Situación de Revista 2', 'fromm': 254, 'long': 2},
    {'id': 458, 'name': 'Situación de Revista 3', 'fromm': 256, 'long': 2},
    {'id': 459, 'name': 'Dia inicio Situación de Revista 3', 'fromm': 258, 'long': 2},
    {'id': 460, 'name': 'Sueldo + Adicionales', 'fromm': 260, 'long': 12},
    {'id': 461, 'name': 'SAC', 'fromm': 272, 'long': 12},
    {'id': 462, 'name': 'Horas Extra', 'fromm': 284, 'long': 12},
    {'id': 463, 'name': 'Zona desfavorable', 'fromm': 296, 'long': 12},
    {'id': 464, 'name': 'Vacaciones', 'fromm': 308, 'long': 12},
    {'id': 465, 'name': 'Cantidad de días trabajados', 'fromm': 320, 'long': 9},
    {'id': 466, 'name': 'Remuneración Imponible 5', 'fromm': 329, 'long': 12},
    {'id': 467, 'name': 'Trabajador Convencionado 0-No 1-Si', 'fromm': 341, 'long': 1},
    {'id': 468, 'name': 'Remuneración Imponible 6', 'fromm': 342, 'long': 12},
    {'id': 469, 'name': 'Tipo de Operación', 'fromm': 354, 'long': 1},
    {'id': 470, 'name': 'Adicionales', 'fromm': 355, 'long': 12},
    {'id': 471, 'name': 'Premios', 'fromm': 367, 'long': 12},
    {'id': 472, 'name': 'Rem.Dec.788/05 - Rem Impon. 8', 'fromm': 379, 'long': 12},
    {'id': 473, 'name': 'Remuneración Imponible 7', 'fromm': 391, 'long': 12},
    {'id': 474, 'name': 'Cantidad de Horas Extras', 'fromm': 403, 'long': 3},
    {'id': 475, 'name': 'Conceptos no remunerativos', 'fromm': 406, 'long': 12},
    {'id': 476, 'name': 'Maternidad', 'fromm': 418, 'long': 12},
    {'id': 477, 'name': 'Rectificación de remuneración', 'fromm': 430, 'long': 9},
    {'id': 478, 'name': 'Remuneración Imponible 9', 'fromm': 439, 'long': 12},
    {'id': 479, 'name': 'Contribucion tarea diferencial (%)', 'fromm': 451, 'long': 9},
    {'id': 480, 'name': 'Horas trabajadas', 'fromm': 460, 'long': 3},
    {'id': 481, 'name': 'Seguro Colectivo de Vida Obligatorio', 'fromm': 463, 'long': 1},
    {'id': 482, 'name': 'Importe a detraer Ley 27430', 'fromm': 464, 'long': 12},
    {'id': 483, 'name': 'Incremento Salarial', 'fromm': 476, 'long': 12},
    {'id': 484, 'name': 'Remuneración Imponible 11', 'fromm': 488, 'long': 12},
]

TABLA_ORDENREGISTRO = [
    {'id': 81, 'tiporegistro_id': 1, 'formatof931_id': None, 'name': 'Identificacion del tipo de registro', 'fromm': 1, 'long': 2, 'type': 'AL', 'description': "Fijo ''01"},
    {'id': 82, 'tiporegistro_id': 1, 'formatof931_id': None, 'name': 'CUIT del empleador', 'fromm': 3, 'long': 11, 'type': 'NU', 'description': '11 enteros. CUIT del empleador sin guiones.'},
    {'id': 83, 'tiporegistro_id': 1, 'formatof931_id': None, 'name': 'Identificación del envío', 'fromm': 14, 'long': 2, 'type': 'AN', 'description': "Valores permitidos. ''SJ''=Informa la liquidación de SyJ y datos de la DJ F931; ''RE''=Sólo informa datos de la DJ F931 a rectificar"},
    {'id': 84, 'tiporegistro_id': 1, 'formatof931_id': None, 'name': 'Período', 'fromm': 16, 'long': 6, 'type': 'NU', 'description': 'Es el período de la liquidación de SyJ o de la DJ. Formato: AAAAMM'},
    {'id': 85, 'tiporegistro_id': 1, 'formatof931_id': None, 'name': 'Tipo de liquidación', 'fromm': 22, 'long': 1, 'type': 'AN', 'description': None},
    {'id': 86, 'tiporegistro_id': 1, 'formatof931_id': None, 'name': 'Número de liquidación', 'fromm': 23, 'long': 5, 'type': 'NU', 'description': None},
    {'id': 87, 'tiporegistro_id': 1, 'formatof931_id': None, 'name': 'Dias base', 'fromm': 28, 'long': 2, 'type': 'AN', 'description': None},
    {'id': 88, 'tiporegistro_id': 1, 'formatof931_id': None, 'name': "Cantidad de trabajadores informados en registros ''04", 'fromm': 30, 'long': 6, 'type': 'NU', 'description': '6 enteros. Debe coincidir con la cantidad de registros tipo ?04? informados en el archivo (emplados propios y no propios)'},
    {'id': 89, 'tiporegistro_id': 2, 'formatof931_id': None, 'name': 'Identificacion del tipo de registro', 'fromm': 1, 'long': 2, 'type': 'AL', 'description': "Fijo ''02"},
    {'id': 90, 'tiporegistro_id': 2, 'formatof931_id': None, 'name': 'CUIL del trabajador', 'fromm': 3, 'long': 11, 'type': 'NU', 'description': '11 enteros. CUIL del empleado sin guiones.'},
    {'id': 91, 'tiporegistro_id': 2, 'formatof931_id': None, 'name': 'Legajo del trabajador', 'fromm': 14, 'long': 10, 'type': 'AN', 'description': 'Este valor es optativo. De no incluir detalle'},
    {'id': 92, 'tiporegistro_id': 2, 'formatof931_id': None, 'name': 'Dependencia de revista del trabajador', 'fromm': 24, 'long': 50, 'type': 'AN', 'description': 'Es el área donde el trabajador desempeña sus funciones( Ej. departamento de ventas). Este valor es optativo. De no incluir detalle'},
    {'id': 93, 'tiporegistro_id': 2, 'formatof931_id': None, 'name': 'CBU de acreditación del pago', 'fromm': 74, 'long': 22, 'type': 'AN', 'description': 'Se valida de acuerdo a las reglas definidas por el BCRA. Sólo se informa si \\"forma de pago\\" es igual a \'\'3\'\' (acreditación en cuenta)'},
    {'id': 94, 'tiporegistro_id': 2, 'formatof931_id': None, 'name': 'Cantidad de días para proporcionar tope', 'fromm': 96, 'long': 3, 'type': 'NU', 'description': None},
    {'id': 95, 'tiporegistro_id': 2, 'formatof931_id': None, 'name': 'Fecha de pago', 'fromm': 99, 'long': 8, 'type': 'NU', 'description': 'Formato: AAAAMMDD'},
    {'id': 96, 'tiporegistro_id': 2, 'formatof931_id': None, 'name': 'Fecha de rúbrica', 'fromm': 107, 'long': 8, 'type': 'AN', 'description': 'Completar con espacios en blanco.'},
    {'id': 97, 'tiporegistro_id': 2, 'formatof931_id': None, 'name': 'Forma de pago', 'fromm': 115, 'long': 1, 'type': 'AN', 'description': "Valores permitidos. ''1''=Efectivo; ''2''=Cheque; ''3''=Acreditación en cuenta"},
    {'id': 98, 'tiporegistro_id': 3, 'formatof931_id': None, 'name': 'Identificación del tipo de registro', 'fromm': 1, 'long': 2, 'type': 'AL', 'description': "Fijo ''03"},
    {'id': 99, 'tiporegistro_id': 3, 'formatof931_id': None, 'name': 'CUIL del trabajador', 'fromm': 3, 'long': 11, 'type': 'NU', 'description': '11 enteros. CUIL del empleado sin guiones.'},
    {'id': 100, 'tiporegistro_id': 3, 'formatof931_id': None, 'name': 'Código de concepto liquidado por el empleador', 'fromm': 14, 'long': 10, 'type': 'AN', 'description': 'Corresponde al código del concepto del empleador.'},
    {'id': 101, 'tiporegistro_id': 3, 'formatof931_id': None, 'name': 'Cantidad', 'fromm': 24, 'long': 5, 'type': 'NU', 'description': '3 enteros y 2 decimales.\\nEste valor es obligatorio cuando se informa un código de concepto asociado a los siguientes conceptos AFIP:\\n123000-SAC PROPORCIONAL\\n150000-ADELANTO VACACIONAL\\n130000 a 139999-HORAS EXTRAS'},
    {'id': 102, 'tiporegistro_id': 3, 'formatof931_id': None, 'name': 'Unidades', 'fromm': 29, 'long': 1, 'type': 'AN', 'description': 'Tipo de moneda=$; porcentuales=%; A=año; M=mes; Q=quincena; S=semanal; D=días; H=horas. Valor optativo'},
    {'id': 103, 'tiporegistro_id': 3, 'formatof931_id': None, 'name': 'Importe', 'fromm': 30, 'long': 15, 'type': 'NU', 'description': '13 enteros y 2 decimales'},
    {'id': 104, 'tiporegistro_id': 3, 'formatof931_id': None, 'name': 'Indicador Débito / Crédito', 'fromm': 45, 'long': 1, 'type': 'AN', 'description': 'D=Débito; C=Crédito'},
    {'id': 105, 'tiporegistro_id': 3, 'formatof931_id': None, 'name': 'Período de ajuste retroactivo', 'fromm': 46, 'long': 6, 'type': 'AN', 'description': None},
    {'id': 106, 'tiporegistro_id': 4, 'formatof931_id': None, 'name': 'Identificación del tipo de registro', 'fromm': 1, 'long': 2, 'type': 'NU', 'description': "Fijo ''04"},
    {'id': 107, 'tiporegistro_id': 4, 'formatof931_id': 425, 'name': 'CUIL', 'fromm': 3, 'long': 11, 'type': 'NU', 'description': None},
    {'id': 108, 'tiporegistro_id': 4, 'formatof931_id': 427, 'name': 'Cónyuge', 'fromm': 14, 'long': 1, 'type': 'AN', 'description': None},
    {'id': 109, 'tiporegistro_id': 4, 'formatof931_id': 428, 'name': 'Cantidad de hijos', 'fromm': 15, 'long': 2, 'type': 'NU', 'description': None},
    {'id': 110, 'tiporegistro_id': 4, 'formatof931_id': 467, 'name': 'Marca CCT', 'fromm': 17, 'long': 1, 'type': 'AN', 'description': None},
    {'id': 111, 'tiporegistro_id': 4, 'formatof931_id': 481, 'name': 'Marca SCVO', 'fromm': 18, 'long': 1, 'type': 'AN', 'description': None},
    {'id': 112, 'tiporegistro_id': 4, 'formatof931_id': 449, 'name': 'Marca corresponde reducción', 'fromm': 19, 'long': 1, 'type': 'AN', 'description': None},
    {'id': 113, 'tiporegistro_id': 4, 'formatof931_id': 451, 'name': 'Código de tipo de empleador asociado al trabajador', 'fromm': 20, 'long': 1, 'type': 'AN', 'description': None},
    {'id': 114, 'tiporegistro_id': 4, 'formatof931_id': 469, 'name': 'Código de tipo de operación', 'fromm': 21, 'long': 1, 'type': 'AN', 'description': 'Valor fijo: ?0?'},
    {'id': 115, 'tiporegistro_id': 4, 'formatof931_id': 429, 'name': 'Código de situación de revista', 'fromm': 22, 'long': 2, 'type': 'AN', 'description': 'Valores permitidos: los existentes en la tabla ?Situación de Revista? de Declaración en Línea.'},
    {'id': 116, 'tiporegistro_id': 4, 'formatof931_id': 430, 'name': 'Código de condición', 'fromm': 24, 'long': 2, 'type': 'AN', 'description': 'Valores permitidos: los existentes en la tabla ?Código de Condición? de Declaración en Línea.'},
    {'id': 117, 'tiporegistro_id': 4, 'formatof931_id': 431, 'name': 'Código de actividad', 'fromm': 26, 'long': 3, 'type': 'AN', 'description': 'Valores permitidos: los existentes en la tabla ?Actividades? de Declaración en Línea.'},
    {'id': 118, 'tiporegistro_id': 4, 'formatof931_id': 434, 'name': 'Código de modalidad de contratación', 'fromm': 29, 'long': 3, 'type': 'AN', 'description': 'Valores permitidos: los existentes en la tabla ?Modalidades de Contratación? de Declaración en Línea.'},
    {'id': 119, 'tiporegistro_id': 4, 'formatof931_id': 448, 'name': 'Código de siniestrado', 'fromm': 32, 'long': 2, 'type': 'AN', 'description': 'Valores permitidos: los existentes en la tabla ?Siniestrados? de Declaración en Línea.'},
    {'id': 120, 'tiporegistro_id': 4, 'formatof931_id': 432, 'name': 'Código de localidad', 'fromm': 34, 'long': 2, 'type': 'AN', 'description': 'Valores permitidos: los existentes en la tabla ?Localidades Geográficas? de Declaración en Línea.'},
    {'id': 121, 'tiporegistro_id': 4, 'formatof931_id': 454, 'name': 'Situación de revista 1', 'fromm': 36, 'long': 2, 'type': 'AN', 'description': 'Valores permitidos: los existentes en la tabla ?Situación de Revista? de Declaración en Línea.'},
    {'id': 122, 'tiporegistro_id': 4, 'formatof931_id': 455, 'name': 'Día de inicio situación de revista 1', 'fromm': 38, 'long': 2, 'type': 'NU', 'description': '2 enteros. Día inicial para la situación de revista 1.'},
    {'id': 123, 'tiporegistro_id': 4, 'formatof931_id': 456, 'name': 'Situación de revista 2', 'fromm': 40, 'long': 2, 'type': 'AN', 'description': 'Valores permitidos: los existentes en la tabla ?Situación de Revista? de Declaración en Línea.'},
    {'id': 124, 'tiporegistro_id': 4, 'formatof931_id': 457, 'name': 'Día de inicio situación de revista 2', 'fromm': 42, 'long': 2, 'type': 'NU', 'description': '2 enteros. Día inicial para la situación de revista 2.'},
    {'id': 125, 'tiporegistro_id': 4, 'formatof931_id': 458, 'name': 'Situación de revista 3', 'fromm': 44, 'long': 2, 'type': 'AN', 'description': 'Valores permitidos: los existentes en la tabla ?Situación de Revista? de Declaración en Línea.'},
    {'id': 126, 'tiporegistro_id': 4, 'formatof931_id': 459, 'name': 'Día de inicio situación de revista 3', 'fromm': 46, 'long': 2, 'type': 'NU', 'description': '2 enteros. Día inicial para la situación de revista 3.'},
    {'id': 127, 'tiporegistro_id': 4, 'formatof931_id': 465, 'name': 'Cantidad de días trabajados', 'fromm': 48, 'long': 2, 'type': 'NU', 'description': '2 enteros.'},
    {'id': 128, 'tiporegistro_id': 4, 'formatof931_id': 480, 'name': 'Cantidad de horas trabajadas', 'fromm': 50, 'long': 3, 'type': 'NU', 'description': None},
    {'id': 129, 'tiporegistro_id': 4, 'formatof931_id': 433, 'name': 'Porcentaje de aporte adicional de seguridad social', 'fromm': 53, 'long': 5, 'type': 'NU', 'description': '3 enteros y 2 decimales. Formato 99999. Las últimas dos posiciones corresponden a los centavos del importe.'},
    {'id': 130, 'tiporegistro_id': 4, 'formatof931_id': 479, 'name': 'Porcentaje de contribución por tarea diferencial', 'fromm': 58, 'long': 5, 'type': 'NU', 'description': '3 enteros y 2 decimales. Formato 99999. Las últimas dos posiciones corresponden a los centavos del importe.'},
    {'id': 131, 'tiporegistro_id': 4, 'formatof931_id': 435, 'name': 'Código de obra social del trabajador', 'fromm': 63, 'long': 6, 'type': 'AN', 'description': 'Según tabla de codificación RNOS'},
    {'id': 132, 'tiporegistro_id': 4, 'formatof931_id': 436, 'name': 'Cantidad de adherentes de obra social', 'fromm': 69, 'long': 2, 'type': 'NU', 'description': '2 enteros.'},
    {'id': 133, 'tiporegistro_id': 4, 'formatof931_id': 452, 'name': 'Aporte adicional de obra social', 'fromm': 71, 'long': 15, 'type': 'NU', 'description': None},
    {'id': 134, 'tiporegistro_id': 4, 'formatof931_id': 441, 'name': 'Contribución adicional de obra social', 'fromm': 86, 'long': 15, 'type': 'NU', 'description': None},
    {'id': 135, 'tiporegistro_id': 4, 'formatof931_id': None, 'name': 'Base para el cálculo diferencial de aporte de obra social y FSR (1)', 'fromm': 101, 'long': 15, 'type': 'NU', 'description': None},
    {'id': 136, 'tiporegistro_id': 4, 'formatof931_id': None, 'name': 'Base para el cálculo diferencial de contribuciones de obra social y FSR (1)', 'fromm': 116, 'long': 15, 'type': 'NU', 'description': None},
    {'id': 137, 'tiporegistro_id': 4, 'formatof931_id': None, 'name': 'Base para el cálculo diferencial Ley de Riesgos del Trabajo (1)', 'fromm': 131, 'long': 15, 'type': 'NU', 'description': None},
    {'id': 138, 'tiporegistro_id': 4, 'formatof931_id': 476, 'name': 'Remuneración maternidad para ANSeS', 'fromm': 146, 'long': 15, 'type': 'NU', 'description': None},
    {'id': 139, 'tiporegistro_id': 4, 'formatof931_id': 437, 'name': 'Remuneración bruta', 'fromm': 161, 'long': 15, 'type': 'NU', 'description': None},
    {'id': 140, 'tiporegistro_id': 4, 'formatof931_id': 438, 'name': 'Base imponible 1', 'fromm': 176, 'long': 15, 'type': 'NU', 'description': None},
    {'id': 141, 'tiporegistro_id': 4, 'formatof931_id': 445, 'name': 'Base imponible 2', 'fromm': 191, 'long': 15, 'type': 'NU', 'description': None},
    {'id': 142, 'tiporegistro_id': 4, 'formatof931_id': 446, 'name': 'Base imponible 3', 'fromm': 206, 'long': 15, 'type': 'NU', 'description': None},
    {'id': 143, 'tiporegistro_id': 4, 'formatof931_id': 447, 'name': 'Base imponible 4', 'fromm': 221, 'long': 15, 'type': 'NU', 'description': None},
    {'id': 144, 'tiporegistro_id': 4, 'formatof931_id': 466, 'name': 'Base imponible 5', 'fromm': 236, 'long': 15, 'type': 'NU', 'description': None},
    {'id': 145, 'tiporegistro_id': 4, 'formatof931_id': 468, 'name': 'Base imponible 6', 'fromm': 251, 'long': 15, 'type': 'NU', 'description': None},
    {'id': 146, 'tiporegistro_id': 4, 'formatof931_id': 473, 'name': 'Base imponible 7', 'fromm': 266, 'long': 15, 'type': 'NU', 'description': None},
    {'id': 147, 'tiporegistro_id': 4, 'formatof931_id': 472, 'name': 'Base imponible 8', 'fromm': 281, 'long': 15, 'type': 'NU', 'description': None},
    {'id': 148, 'tiporegistro_id': 4, 'formatof931_id': 478, 'name': 'Base imponible 9', 'fromm': 296, 'long': 15, 'type': 'NU', 'description': None},
    {'id': 149, 'tiporegistro_id': 4, 'formatof931_id': None, 'name': 'Base para el cálculo diferencial de aporte de Seg. Social', 'fromm': 311, 'long': 15, 'type': 'NU', 'description': None},
    {'id': 150, 'tiporegistro_id': 4, 'formatof931_id': None, 'name': 'Base para el cálculo diferencial de contribuciones de Seg. Social', 'fromm': 326, 'long': 15, 'type': 'NU', 'description': None},
    {'id': 151, 'tiporegistro_id': 4, 'formatof931_id': None, 'name': 'Base imponible 10', 'fromm': 341, 'long': 15, 'type': 'NU', 'description': None},
    {'id': 152, 'tiporegistro_id': 4, 'formatof931_id': 482, 'name': 'Importe a detraer (Ley 26.473)', 'fromm': 356, 'long': 15, 'type': 'NU', 'description': None},
    {'id': 153, 'tiporegistro_id': 5, 'formatof931_id': None, 'name': 'Identificacion del tipo de registro', 'fromm': 1, 'long': 2, 'type': 'AN', 'description': "Fijo ''05"},
    {'id': 154, 'tiporegistro_id': 5, 'formatof931_id': None, 'name': 'CUIL del trabajador', 'fromm': 3, 'long': 11, 'type': 'NU', 'description': '11 enteros. CUIL del empleado sin guiones.'},
    {'id': 155, 'tiporegistro_id': 5, 'formatof931_id': None, 'name': 'Categoría profesional', 'fromm': 14, 'long': 6, 'type': 'NU', 'description': 'Según tabla de codificación específica de Simplificación registral.'},
    {'id': 156, 'tiporegistro_id': 5, 'formatof931_id': None, 'name': 'Puesto desempeñado', 'fromm': 20, 'long': 4, 'type': 'AN', 'description': 'Según tabla de codificación específica de Simplificación registral.'},
    {'id': 157, 'tiporegistro_id': 5, 'formatof931_id': None, 'name': 'Fecha de ingreso', 'fromm': 24, 'long': 8, 'type': 'NU', 'description': 'Formato: AAAAMMDD.\\nEs la fecha dentro del período declarado en la que inicia la prestación de servicios en la Empresa Usuaria.\\nPuede haber iniciado su relación laboral en meses anteriores.'},
    {'id': 158, 'tiporegistro_id': 5, 'formatof931_id': None, 'name': 'Fecha de egreso', 'fromm': 32, 'long': 8, 'type': 'NU', 'description': 'Formato: AAAAMMDD.\\nEs la fecha en la que finaliza dentro del período declarado la prestación de servicios en la Empresa Usuaria.\\nPuede continuar la relación el mes siguiente.'},
    {'id': 159, 'tiporegistro_id': 5, 'formatof931_id': None, 'name': 'Remuneración', 'fromm': 40, 'long': 15, 'type': 'NU', 'description': 'Debe coincidir con la base imponible 9'},
    {'id': 160, 'tiporegistro_id': 5, 'formatof931_id': None, 'name': 'CUIT del empleador', 'fromm': 55, 'long': 11, 'type': 'NU', 'description': 'Las empresas usuarias deben informar el CUIT de la empresa de servicios eventuales.'},
]
