name: Development Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Django Tests and Linting]
    types:
      - completed
    branches:
      - develop

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Copy files to EC2
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "/home/ubuntu/app"

      # 3️⃣ Create .env on EC2 from secrets
      - name: Create .env on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cat > /home/ubuntu/app/.env <<EOF
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
            POSTGRES_HOST=postgres_service
            ALLOW_ORIGINS=${{ vars.ALLOW_ORIGINS }}
            DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
            ENV=develop
            EOF

      # 4️⃣ SSH into EC2 and deploy Docker container
      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/app
            export GIT_COMMIT=${{ github.sha }}
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml up -d --build
            docker system prune -f
