name: Django CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.14"]

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: uv sync --dev
    - name: Check pending migrations
      run: |
        uv run python manage.py makemigrations --check --dry-run
        uv run python manage.py migrate

    # - name: Check pending static files to collect
    #   run: |
    #     uv run python manage.py collectstatic --noinput
    #     git diff --exit-code static/

    - name: Lint with Flake8
      run: uv run flake8  # config in pyproject.toml [tool.flake8]

    - name: Run Tests
      run: uv run python manage.py test
